# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  twitter_provider_key: <%= ENV["TWITTER_PROVIDER_KEY"] %>
  twitter_provider_secret: <%= ENV["TWITTER_PROVIDER_SECRET"] %>
  google_provider_key: <%= ENV["GOOGLE_PROVIDER_KEY"] %>
  google_provider_secret: <%= ENV["GOOGLE_PROVIDER_SECRET"] %>
  github_provider_key: <%= ENV["GITHUB_PROVIDER_KEY"] %>
  github_provider_secret: <%= ENV["GITHUB_PROVIDER_SECRET"] %>
  azuread_provider_key: <%= ENV["AZUREAD_PROVIDER_KEY"] %>
  azuread_provider_tenant: <%= ENV["AZUREAD_PROVIDER_TENANT"] %>
  domain_name: example.com
  secret_key_base: 499ed5cb646ed762eb3ef0c7e897e4faa3e79b683d7e6c83a1d33e79aac0b0b665915c7d457514b4960d8bb8448d80a863caf5c16b851be57a2192f6da202000

test:
  secret_key_base: 3d64e1305376b7cc8621ac595c405e44cdd96ad4c1f7994d637a56311ab775f65f96883d1871b7ae9098f85bebeb8f9f7b88e9586b583fb73e229624bc0af152

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  twitter_provider_key: <%= ENV["TWITTER_PROVIDER_KEY"] %>
  twitter_provider_secret: <%= ENV["TWITTER_PROVIDER_SECRET"] %>
  google_provider_key: <%= ENV["GOOGLE_PROVIDER_KEY"] %>
  google_provider_secret: <%= ENV["GOOGLE_PROVIDER_SECRET"] %>
  github_provider_key: <%= ENV["GITHUB_PROVIDER_KEY"] %>
  github_provider_secret: <%= ENV["GITHUB_PROVIDER_SECRET"] %>
  azuread_provider_key: <%= ENV["AZUREAD_PROVIDER_KEY"] %>
  azuread_provider_tenant: <%= ENV["AZUREAD_PROVIDER_TENANT"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  twitter_provider_key: <%= ENV["TWITTER_PROVIDER_KEY"] %>
  twitter_provider_secret: <%= ENV["TWITTER_PROVIDER_SECRET"] %>
  google_provider_key: <%= ENV["GOOGLE_PROVIDER_KEY"] %>
  google_provider_secret: <%= ENV["GOOGLE_PROVIDER_SECRET"] %>
  github_provider_key: <%= ENV["GITHUB_PROVIDER_KEY"] %>
  github_provider_secret: <%= ENV["GITHUB_PROVIDER_SECRET"] %>
  azuread_provider_key: <%= ENV["AZUREAD_PROVIDER_KEY"] %>
  azuread_provider_tenant: <%= ENV["AZUREAD_PROVIDER_TENANT"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
